version: '3'

volumes:
  mariadb-data:
  gem-home:

networks:
  default:
  #database:
  #  external: true

services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_development
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - mariadb-data:/var/lib/mysql
      #- ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
      #- database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  rails:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - "RAILS_ENV=development"
    volumes:
      - ./project:/usr/src/app
      - gem-home:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - default
      #- database
    # command: 

