version: '3'

volumes:
  mariadb_data:
  gem_home:

networks:
  default:

services:
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_development
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    volumes:
      - mariadb_data:/var/lib/mysql
      #- ./mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - default
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  rails:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - "RAILS_ENV=development"
    env_file: .env
    volumes:
      - ./data/project:/usr/src/project
      - gem_home:/usr/local/bundle
    ports:
      - 3000:3000 
    networks:
      - default
