version: '3'

services:
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_development
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
      - mariadb_default
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON

  rails:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - "RAILS_ENV=development"
    volumes:
      - "./project:/usr/src/app"
    ports:
      - '3000:3000'
    networks:
      - default
      - mariadb_default
    # command: 

networks:
  default:
  mariadb_default: